# Generated by Django 4.2.11 on 2024-03-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campaign',
            table='campaign',
        ),
        migrations.AlterModelTable(
            name='campaignowner',
            table='campaign_owner',
        ),
        migrations.AlterModelTable(
            name='owner',
            table='owner',
        ),
        migrations.AlterModelTable(
            name='targetaudience',
            table='target_audience',
        ),
    ]
