# Generated by Django 4.2.11 on 2024-03-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_table_alter_campaignowner_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
